### ISSUE TITLE
Structure as to pypi standards.

### ISSUE THREAD

**Issue by LinuxIsCool** [longtailfinancial/TokenEngineering#1]
Here is a reference example:

![image](https://user-images.githubusercontent.com/31582215/123867453-3ac38500-d8e3-11eb-88c4-e725ebaa84f3.png)

From:
https://github.com/longtailfinancial/te-library-publishing/tree/main/ltfte-library

**Comment by JohannSuarez** [comment]
Hi Shawn! I just took a second look at this and realized that this repo (or at least the packaging branch) doesn't need to be structured as such. The layout above is for staging a PyPI package/library, and not for the active development of one.
With the layout we have now in the packaging branch, it's perfect for being git cloned (as a submodule) into the boilerplate needed to publish it to PyPI. 
All is well!
