### ISSUE TITLE
Inflation premium should be able to be negative. This is the case if the underlying cash is deflationairy. 

### ISSUE THREAD

**Issue by LinuxIsCool** [longtailfinancial/TokenEngineering#4]
https://github.com/longtailfinancial/TokenEngineering/blob/3e255328d592ccd59915017755f3a3cae441187a/quantitativeinvestmentanalysis/qia.py#L30

**Comment by LinuxIsCool** [comment]
Alternatively, we could consider all cash flow operations to be running on Fiat..

**Comment by JohannSuarez** [comment]
Inflation premium lower bound removed. It can now be negative.
