### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by LinuxIsCool** [longtailfinancial/TokenEngineering#9]

**Comment by LinuxIsCool** [comment]
Ahh, from @dahn510 in discord:

Install the LTF TE library.  
`pip install ltfte`

**Comment by dahn510** [comment]
Upon further investigation this is not the distribution repo. 
[te-library-publishing](https://github.com/longtailfinancial/te-library-publishing) is distributed on pypi.
The documentation explains the usage but needs to be updated.
